// Dados mock para o protótipo
import type { 
  User, 
  Opportunity, 
  ApprovalRequest, 
  Certificate, 
  Group, 
  PPC, 
  Notification,
  DashboardMetrics 
} from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao.silva@discente.ufma.br',
    registration: '202012345',
    roles: ['discente'],
    course: 'Ciência da Computação',
    semester: 6,
  },
  {
    id: '2',
    name: 'Prof.ª Maria Souza',
    email: 'maria.souza@docente.ufma.br',
    registration: '123456',
    roles: ['docente'],
  },
  {
    id: '3',
    name: 'Dr. Carlos Mendes',
    email: 'carlos.mendes@docente.ufma.br',
    registration: '789012',
    roles: ['coordenador', 'docente'],
  },
  {
    id: '4',
    name: 'Ana Paula Lima',
    email: 'ana.lima@docente.ufma.br',
    registration: '345678',
    roles: ['secretaria'],
  },
  {
    id: '5',
    name: 'Roberto Admin',
    email: 'roberto.admin@docente.ufma.br',
    registration: '999999',
    roles: ['administrador'],
  },
];

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp1',
    title: 'Oficina de Fotografia',
    description: 'Aprenda técnicas básicas e avançadas de fotografia digital. Inclui teoria e prática com equipamentos profissionais.',
    modality: 'oficina',
    workload: 20,
    startDate: '2025-06-15',
    endDate: '2025-07-15',
    vacancies: 30,
    availableVacancies: 12,
    status: 'aberta',
    responsibleId: '2',
    responsibleName: 'Prof.ª Maria Souza',
    createdBy: '2',
    createdAt: '2025-05-10',
    participants: [
      {
        userId: '1',
        userName: 'João Silva',
        userEmail: 'joao.silva@dicente.ufma.br',
        status: 'aprovado',
        enrolledAt: '2025-05-15',
        completedHours: 8,
      },
    ],
  },
  {
    id: 'opp2',
    title: 'Projeto Horta Comunitária',
    description: 'Projeto de extensão para criar e manter uma horta comunitária no bairro Vila Nova.',
    modality: 'projeto',
    workload: 40,
    startDate: '2025-08-01',
    endDate: '2025-12-15',
    vacancies: 15,
    availableVacancies: 15,
    status: 'publicada',
    responsibleId: '3',
    responsibleName: 'Dr. Carlos Mendes',
    createdBy: '3',
    createdAt: '2025-06-01',
  },
  {
    id: 'opp3',
    title: 'Curso de Programação para Idosos',
    description: 'Ensinar noções básicas de informática e programação para a terceira idade.',
    modality: 'curso',
    workload: 30,
    startDate: '2025-07-10',
    endDate: '2025-09-10',
    vacancies: 20,
    availableVacancies: 5,
    status: 'aberta',
    responsibleId: '2',
    responsibleName: 'Prof.ª Maria Souza',
    createdBy: '1',
    createdAt: '2025-06-05',
  },
  {
    id: 'opp4',
    title: 'Workshop de Design Thinking',
    description: 'Workshop intensivo sobre metodologias ágeis e design thinking aplicado a projetos sociais.',
    modality: 'evento',
    workload: 8,
    startDate: '2025-11-20',
    endDate: '2025-11-20',
    vacancies: 50,
    availableVacancies: 50,
    status: 'publicada',
    responsibleId: '3',
    responsibleName: 'Dr. Carlos Mendes',
    createdBy: '3',
    createdAt: '2025-06-08',
  },
  {
    id: 'opp5',
    title: 'Minha Primeira Oficina',
    description: 'Oficina criada como teste pelos alunos.',
    modality: 'oficina',
    workload: 10,
    startDate: '2025-08-01',
    endDate: '2025-08-15',
    vacancies: 10,
    availableVacancies: 10,
    status: 'rascunho',
    responsibleId: '1',
    responsibleName: 'João Silva',
    createdBy: '1',
    createdAt: '2025-06-10',
  },
];

export const mockApprovalRequests: ApprovalRequest[] = [
  {
    id: 'req1',
    userId: '1',
    userName: 'João Silva',
    userEmail: 'joao.silva@dicente.ufma.br',
    description: 'Participação em curso de Primeiros Socorros oferecido pela Cruz Vermelha',
    requestedHours: 16,
    certificateFile: 'certificado-primeiros-socorros.pdf',
    certificateMetadata: {
      issuer: 'Cruz Vermelha Brasileira',
      date: '2025-05-20',
      title: 'Curso de Primeiros Socorros',
    },
    status: 'pendente',
    submittedAt: '2025-06-01',
    deadline: '2025-06-11',
  },
  {
    id: 'req2',
    userId: '1',
    userName: 'João Silva',
    userEmail: 'joao.silva@dicente.ufma.br',
    description: 'Voluntariado em campanha de vacinação - posto de saúde central',
    requestedHours: 12,
    certificateFile: 'declaracao-voluntariado.pdf',
    certificateMetadata: {
      issuer: 'Secretaria Municipal de Saúde',
      date: '2025-04-15',
      title: 'Campanha de Vacinação 2025',
    },
    status: 'aprovado',
    submittedAt: '2025-05-10',
    reviewedAt: '2025-05-15',
    reviewedBy: '3',
    reviewerName: 'Dr. Carlos Mendes',
    decision: 'aprovado',
    feedback: 'Atividade aprovada. Documento comprobatório válido.',
  },
  {
    id: 'req3',
    userId: '1',
    userName: 'João Silva',
    userEmail: 'joao.silva@dicente.ufma.br',
    description: 'Workshop sobre sustentabilidade',
    requestedHours: 4,
    certificateFile: 'certificado-workshop.pdf',
    certificateMetadata: {
      issuer: 'ONG Verde Mais',
      date: '2025-03-10',
      title: 'Workshop de Sustentabilidade',
    },
    status: 'indeferido',
    submittedAt: '2025-04-05',
    reviewedAt: '2025-04-10',
    reviewedBy: '3',
    reviewerName: 'Dr. Carlos Mendes',
    decision: 'indeferido',
    feedback: 'A carga horária não está claramente especificada no documento. Por favor, anexe um certificado com a carga horária detalhada.',
  },
];

export const mockCertificates: Certificate[] = [
  {
    id: 'cert1',
    code: 'EXT-2025-001234',
    userId: '1',
    userName: 'João Silva',
    opportunityId: 'opp2',
    opportunityTitle: 'Voluntariado em campanha de vacinação',
    workload: 12,
    issueDate: '2025-05-16',
    qrCode: 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=EXT-2025-001234',
  },
  {
    id: 'cert2',
    code: 'EXT-2025-001567',
    userId: '1',
    userName: 'João Silva',
    opportunityId: 'opp1',
    opportunityTitle: 'Oficina de Fotografia (em andamento)',
    workload: 8,
    issueDate: '2025-06-10',
    qrCode: 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=EXT-2025-001567',
  },
];

export const mockGroups: Group[] = [
  {
    id: 'grp1',
    name: 'Grupo de Extensão em Tecnologia Social',
    description: 'Desenvolvimento de soluções tecnológicas para comunidades carentes',
    email: 'extensao.tech@universidade.edu.br',
    responsibleId: '2',
    responsibleName: 'Prof.ª Maria Souza',
    members: [
      { userId: '1', userName: 'João Silva', role: 'Coordenador de Projetos', joinedAt: '2025-03-01' },
    ],
    createdAt: '2025-02-15',
  },
];

export const mockPPC: PPC[] = [
  {
    id: 'ppc1',
    version: '2024.1',
    minimumWorkload: 60,
    createdBy: '3',
    createdAt: '2024-01-10',
    effectiveFrom: '2024-02-01',
    effectiveUntil: '2024-12-31',
  },
  {
    id: 'ppc2',
    version: '2025.1',
    minimumWorkload: 80,
    createdBy: '3',
    createdAt: '2024-11-15',
    effectiveFrom: '2025-01-01',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'not1',
    userId: '1',
    type: 'success',
    title: 'Inscrição aprovada',
    message: 'Sua inscrição na "Oficina de Fotografia" foi aprovada. Ver detalhes.',
    read: false,
    createdAt: '2025-06-08T10:30:00',
    actionUrl: '/opportunities/opp1',
  },
  {
    id: 'not2',
    userId: '1',
    type: 'info',
    title: 'Novo certificado disponível',
    message: 'Seu certificado de "Voluntariado em campanha de vacinação" está disponível para download.',
    read: false,
    createdAt: '2025-06-07T14:20:00',
    actionUrl: '/certificates',
  },
  {
    id: 'not3',
    userId: '1',
    type: 'warning',
    title: 'Prazo próximo',
    message: 'Sua solicitação de aproveitamento está próxima do prazo de análise (2 dias restantes).',
    read: true,
    createdAt: '2025-06-05T09:15:00',
  },
  {
    id: 'not4',
    userId: '3',
    type: 'info',
    title: 'Nova solicitação de aproveitamento',
    message: 'João Silva enviou uma solicitação de aproveitamento de 16 horas.',
    read: false,
    createdAt: '2025-06-01T11:45:00',
    actionUrl: '/approval-requests',
  },
];

export const mockDashboardMetrics: Record<string, DashboardMetrics> = {
  '1': { // João Silva (Discente)
    completedHours: 24,
    pendingHours: 16,
    totalRequired: 80,
    certificates: 2,
    pendingRequests: 1,
    activeOpportunities: 1,
  },
  '2': { // Prof.ª Maria Souza (Docente)
    completedHours: 0,
    pendingHours: 0,
    totalRequired: 0,
    certificates: 0,
    pendingRequests: 0,
    activeOpportunities: 2,
  },
  '3': { // Dr. Carlos Mendes (Coordenador)
    completedHours: 0,
    pendingHours: 0,
    totalRequired: 0,
    certificates: 0,
    pendingRequests: 1,
    activeOpportunities: 2,
  },
};

// Função para validar certificado (simulação)
export function validateCertificate(code: string): Certificate | null {
  return mockCertificates.find(cert => cert.code === code) || null;
}
